/**********************************************************************************************************************
 * \file cantp.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cantp.h"
#include "uds.h" // 재조립 완료 후 UDS 계층 함수를 호출
#include "can.h"
#include "uart.h"
#include <string.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define FLOW_CONTROL_SEPARATION_TIME_MS 0x0F // 15ms

/*********************************************************************************************************************/
/*------------------------------------------------Type Definition----------------------------------------------------*/
/*********************************************************************************************************************/
//typedef enum {
//    CANTP_SESSION_STATE_IDLE = 0,
//    CANTP_SESSION_STATE_RECEIVING,
//    CANTP_SESSION_STATE_SENDING
//} CANTP_SessionState;
//
//typedef struct {
//    CANTP_SessionState state;
//    uint16 rxTotalSize;
//    uint8 rxConsecutiveSeqNum;
//    uint8 rxBuffer[CANTP_RX_BUFFER_SIZE];
//    uint16 rxBufferCounter;
//    uint8_t rxBlockFrameCount;
//
//    uint16 txTotalSize;
//    uint16 txBufferCounter;
//    uint8 *txBuffer;
//    uint8 txConsecutiveSeqNum;
//} CANTP_Session;

//typedef enum {
//    CANTP_FRAME_TYPE_SINGLE_FRAME = 0x0,
//    CANTP_FRAME_TYPE_FIRST_FRAME = 0x1,
//    CANTP_FRAME_TYPE_CONSECUTIVE_FRAME = 0x2,
//    CANTP_FRAME_TYPE_FLOW_CONTROL = 0x3
//} CANTP_FrameType;

//typedef enum {
//    CANTP_FLOW_STATUS_CONTINUE = 0,
//    CANTP_FLOW_STATUS_WAIT = 1,
//    CANTP_FLOW_STATUS_OVERFLOW = 2
//} CANTP_FlowStatus;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
// --- 수신(Rx) 상태 관리 변수 ---
static volatile IsoTpState g_iso_tp_rx_state = ISO_TP_STATE_IDLE;
static volatile uint16_t g_uds_rx_total_size = 0;
static volatile uint8_t g_rx_expected_seq_num = 0;
static volatile uint8_t g_uds_rx_buffer[CANTP_RX_BUFFER_SIZE];
static volatile uint16_t g_uds_rx_received_size = 0;
static volatile uint16_t g_rx_block_frame_count = 0;

// --- 송신(Tx) 상태 관리 변수 ---
static volatile IsoTpState g_iso_tp_tx_state = ISO_TP_STATE_IDLE;
static volatile uint8_t g_uds_tx_buffer[CANTP_TX_BUFFER_SIZE];
static volatile uint16_t g_uds_tx_total_size = 0;
static volatile uint16_t g_uds_tx_sent_size = 0;
static volatile uint8_t g_tx_seq_num = 0;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void sendSingleFrame(const uint8_t* data, uint16_t length);
void sendFirstFrame(const uint8_t* data, uint16_t length);
void sendFlowControl(uint8_t flowStatus, uint8_t blockSize, uint8_t separationTime);


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* ---- UDS 응답 전송 시작 함수 ---- */
void CANTP_SendResponse(const uint8_t* data, uint16_t length) {
    if (g_iso_tp_tx_state != ISO_TP_STATE_IDLE) return; // 전송 중이면 무시

    if (length <= 7) { // Single Frame
        sendSingleFrame(data, length);

    } else { // First Frame
        sendFirstFrame(data, length);
    }
}

void handleSingleFrame(const unsigned char* canData) {
    if (g_iso_tp_rx_state == ISO_TP_STATE_IDLE) {
        uint8_t msg_len = canData[0] & 0x0F;
        UDS_HandleMessage(&canData[1], msg_len);
    }
}

void handleFirstFrame(const unsigned char* canData) {
    if (g_iso_tp_rx_state == ISO_TP_STATE_IDLE) {
        memset((void*)g_uds_rx_buffer, 0, CANTP_RX_BUFFER_SIZE);

        g_uds_rx_total_size = ((canData[0] & 0x0F) << 8) | canData[1];
        memcpy((void*)g_uds_rx_buffer, &canData[2], 6);
        g_uds_rx_received_size = 6;
        g_rx_expected_seq_num = 1;

        g_rx_block_frame_count = 0;
        g_iso_tp_rx_state = ISO_TP_STATE_WAIT_CF;

        sendFlowControl(0, FLOW_CONTROL_BLOCK_SIZE, FLOW_CONTROL_SEPARATION_TIME_MS); // FS=0 (Continue)
    }
}

void handleConsecutiveFrame(const unsigned char* canData) {
    if (g_iso_tp_rx_state != ISO_TP_STATE_WAIT_CF) {
        return; // 예상치 못한 프레임
    }

    uint8_t sequenceNumber = canData[0] & 0x0F;

    if (sequenceNumber == g_rx_expected_seq_num) {
        uint16_t remainingBytes = g_uds_rx_total_size - g_uds_rx_received_size;
        uint8_t bytesToCopy = (remainingBytes > 7) ? 7 : remainingBytes;

        memcpy(&g_uds_rx_buffer[g_uds_rx_received_size], &canData[1], bytesToCopy);

        g_uds_rx_received_size += bytesToCopy;
        g_rx_expected_seq_num = (g_rx_expected_seq_num + 1) % 16; // 15 다음에는 0으로 돌아감

        g_rx_block_frame_count++;

        if (g_uds_rx_received_size >= g_uds_rx_total_size) {
            // 모든 데이터 조각을 다 받았는지 확인
            // ****** debug ******
            myPrintf("\n--- Multi-frame Message Reassembled ---\n");
            myPrintf("Total Length: %d bytes\n", g_uds_rx_total_size);
//            myPrintf("Data: ");
//            for (int i = 0; i < g_uds_rx_total_size; i++) {
//                myPrintf("%02X ", g_uds_rx_buffer[i]);
//            }
            myPrintf("\n---------receive all consecutive frame--------\n\n");

            UDS_HandleMessage((uint8_t*)g_uds_rx_buffer, g_uds_rx_total_size);

            g_iso_tp_rx_state = ISO_TP_STATE_IDLE;
        } else if (FLOW_CONTROL_BLOCK_SIZE > 0 && g_rx_block_frame_count == FLOW_CONTROL_BLOCK_SIZE) { // 아직 받을 데이터가 남았고, Block Size만큼 프레임을 다 받았다면
            myPrintf("Block complete. Sending next Flow Control.\n");
            g_rx_block_frame_count = 0;
            sendFlowControl(0, FLOW_CONTROL_BLOCK_SIZE, FLOW_CONTROL_SEPARATION_TIME_MS);
        }
    } else {
        g_iso_tp_rx_state = ISO_TP_STATE_IDLE;
        myPrintf("consecutive frame error\n");
    }
}

void handleFlowControl(const unsigned char* canData) {
    if (g_iso_tp_tx_state == ISO_TP_STATE_WAIT_FC){
        if ((canData[0] & 0x0F) == 0){
            g_iso_tp_tx_state = ISO_TP_STATE_SENDING_CF;

            sendConsecutiveFrame();  // CF 중 첫 프레임만 전송
        }
    }
}

/* ---- Consecutive Frame 전송 함수 ---- */
void sendConsecutiveFrame(void) {
    if (g_iso_tp_tx_state == ISO_TP_STATE_SENDING_CF) {
        if (g_uds_tx_sent_size < g_uds_tx_total_size) {
            // 보낼 데이터가 남아있으면 다음 Consecutive Frame(CF) 전송
            uint8_t cfFrame[8] = {0,};
            cfFrame[0] = 0x20 | (g_tx_seq_num & 0x0F);

            uint16_t remainingSize = g_uds_tx_total_size - g_uds_tx_sent_size;
            uint8_t bytesToSend = (remainingSize > 7) ? 7 : remainingSize;

            memcpy(&cfFrame[1], &g_uds_tx_buffer[g_uds_tx_sent_size], bytesToSend);

            canSendMsg(UDS_RESPONSE_CAN_ID, cfFrame, bytesToSend + 1);



            // ****** debug ******
            myPrintf("SEND consecutive frame\n");
            myPrintf("UDS Response ID (0x%X) sent.\n", UDS_RESPONSE_CAN_ID);
//            myPrintf("CanTP Tx: ");
//            for (int i = 0; i < 8; i++)
//            {
//                myPrintf("0x%02X ", cfFrame[i]);
//            }
            myPrintf("\n\n");


            g_uds_tx_sent_size += bytesToSend;
            g_tx_seq_num = (g_tx_seq_num + 1) % 16;
        } else {
            // 모든 데이터 전송 완료
            g_iso_tp_tx_state = ISO_TP_STATE_IDLE;

            // ****** debug ******
            myPrintf("---------send all consecutive frame--------\n\n");
        }
    }
}

/*********************************/
/* ---- single frame 전송 함수 ---- */
void sendSingleFrame(const uint8_t* data, uint16_t length) {
    uint8_t sfFrame[8] = {0,};
    sfFrame[0] = 0x00 | length;    // PCI 생성
    memcpy(&sfFrame[1], data, length); // 실제 데이터 복사

    canSendMsg(UDS_RESPONSE_CAN_ID, sfFrame, 8);


    // ****** debug ******
    myPrintf("SEND single frame\n");
//    myPrintf("CanTP Tx: ");
//    for (int i = 0; i < 8; i++) {
//        myPrintf("0x%02X ", sfFrame[i]);
//    }
    myPrintf("\n---------send single frame--------\n\n");
}

/* ---- First Frame 전송 함수 ---- */
void sendFirstFrame(const uint8_t* data, uint16_t length) {
    memset((void*)g_uds_rx_buffer, 0, CANTP_TX_BUFFER_SIZE);

    memcpy((void*)g_uds_tx_buffer, data, length);
    g_uds_tx_total_size = length;
    g_uds_tx_sent_size = 6;
    g_tx_seq_num = 1;

    uint8_t ffFrame[8] = {0,};
    ffFrame[0] = 0x10 | ((length >> 8) & 0x0F);
    ffFrame[1] = length & 0xFF;
    memcpy(&ffFrame[2], data, 6);

    g_iso_tp_tx_state = ISO_TP_STATE_WAIT_FC;
    canSendMsg(UDS_RESPONSE_CAN_ID, ffFrame, 8); // 첫 프레임 전송 "시작"

    // ****** debug ******
    myPrintf("SEND first frame\n");
//    myPrintf("CanTP Tx: ");
//    for (int i = 0; i < 8; i++)     {
//        myPrintf("0x%02X ", ffFrame[i]);
//    }
    myPrintf("\n---------send first frame--------\n\n");
}

/* ---- Flow Control 프레임 전송 함수 ---- */
void sendFlowControl(uint8_t flowStatus, uint8_t blockSize, uint8_t separationTime) {
    uint8_t fcFrame[8] = {0, };

    // PCI 바이트 생성 (Flow Control Type + Flow Status)
    fcFrame[0] = 0x30 | (flowStatus & 0x0F);
    // Block Size 설정
    fcFrame[1] = blockSize;
    // STmin 설정
    fcFrame[2] = separationTime;

    canSendMsg(UDS_RESPONSE_CAN_ID, fcFrame, 8);



    // ****** debug ******
    myPrintf("SEND flow control frame\n");
    myPrintf("\n---------send flow control--------\n\n");
}

