/**********************************************************************************************************************
 * \file dtchandler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "sidhandler.h"
#include "dtc.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
// 0x19: Read DTC Information Handler
void handleSID19(const uint8_t* data, uint16_t length, const uint8_t sid) {
    // 세션 체크 (Default 이상 허용)
    if (session_getCurrent() < SESSION_DEFAULT) {
        sendNegativeResponse(sid, UDS_NRC_SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION); // 0x7F
        return;
    }

    if (length < 2) { // SID + SubFunction
        sendNegativeResponse(sid, UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT);
        return;
    }

    uint8_t subFunction = data[1];

    if (subFunction == 0x02) { // reportDTCByStatusMask
//        uint8 payload[50];
//        uint16 payloadLength = 0;
//        payload[payloadLength++] = UDS_POSITIVE_RESPONSE_SID(sid);
//        payload[payloadLength++] = subFunction;
//        payload[payloadLength++] = data[2]; //statusMask
//
//        for (int i = 0; i < MAX_DTCS; i++)
//        {
//            if (g_dtcStorage[i].status & DTC_STATUS_TEST_FAILED)
//            {
//                payload[payloadLength++] = (uint8) (g_dtcStorage[i].dtc_code >> 16);
//                payload[payloadLength++] = (uint8) (g_dtcStorage[i].dtc_code >> 8);
//                payload[payloadLength++] = (uint8) (g_dtcStorage[i].dtc_code & 0xFF);
//                payload[payloadLength++] = g_dtcStorage[i].status;
//            }
//        }

        if (length != 3) {
             sendNegativeResponse(sid, UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT);
             return;
        }
        uint8_t statusMask = data[2];

        uint8_t payload[MAX_DTCS * 4 + 3];
        uint16_t payloadLength = 0;

        payload[payloadLength++] = UDS_POSITIVE_RESPONSE_SID(sid); // 0x59
        payload[payloadLength++] = subFunction;                    // 0x02
        payload[payloadLength++] = statusMask;                     // Status Mask 에코

        for (int i = 0; i < MAX_DTCS; i++) {
            if (g_dtcStorage[i].dtc_code != 0 && (g_dtcStorage[i].status & statusMask) != 0) {
                if (payloadLength + 4 <= sizeof(payload)) {
                    payload[payloadLength++] = (uint8_t)(g_dtcStorage[i].dtc_code >> 16);
                    payload[payloadLength++] = (uint8_t)(g_dtcStorage[i].dtc_code >> 8);
                    payload[payloadLength++] = (uint8_t)(g_dtcStorage[i].dtc_code & 0xFF);
                    payload[payloadLength++] = g_dtcStorage[i].status;
                } else {
                    break; // 버퍼 부족
                }
            }
        }

        CANTP_SendResponse(payload, payloadLength);
    }
    else {
        sendNegativeResponse(sid, UDS_NRC_SUB_FUNCTION_NOT_SUPPORTED); // 0x12
    }
}
