/**********************************************************************************************************************
 * \file readdatahandler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "uds.h"       // sendNegativeResponse, UDS_POSITIVE_RESPONSE_SID 등 사용
#include "sidhandler.h"
#include "cantp.h"     // CANTP_SendResponse 사용
#include "tof.h"       // tofGetValue 사용
#include "uart.h"  // myPrintf 사용 (0x2A 핸들러)
#include "stm.h"       // STM 관련 매크로 및 레지스터 접근 (0x2A 핸들러)

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


/*
0x22 (ReadDataByIdentifier),
0x23 (ReadMemoryByAddress),
0x24 (ReadScalingDataByIdentifier),
0x2A (ReadDataByPeriodicIdentifier) 등 데이터 읽기 관련 SID 핸들러 포함.
*/

/* ---- 0x22: Read Data By Identifier Handler ---- */
void handleSID22(const uint8_t* data, uint16_t length, const uint8_t sid) {
    if (length != 3) {
        sendNegativeResponse(sid, UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT);
        return;
    }

    uint16_t did = (data[1] << 8) | data[2];

    switch (did) {
        case UDS_DID_TOF_SENSOR:
        {
            uint32_t currentTofValue = tofGetValue();
            if (currentTofValue != TOF_INVALID_VALUE) {
                uint8_t responseMsg[6];
                responseMsg[0] = UDS_POSITIVE_RESPONSE_SID(sid);
                responseMsg[1] = (did >> 8) & 0xFF;
                responseMsg[2] = did & 0xFF;
                responseMsg[3] = (currentTofValue >> 16) & 0xFF;
                responseMsg[4] = (currentTofValue >> 8) & 0xFF;
                responseMsg[5] = currentTofValue & 0xFF;

                CANTP_SendResponse(responseMsg, sizeof(responseMsg));
            }
            else {
                sendNegativeResponse(sid, UDS_NRC_CONDITIONS_NOT_CORRECT);
            }
            break;
        }
        // 여기에 0x22 서비스로 읽을 다른 DID 케이스 추가
        default:
            sendNegativeResponse(sid, UDS_NRC_REQUEST_OUT_OF_RANGE);
            break;
    }
}

/* ---- 0x2A: Read Data By Periodic Identifier Handler ---- */
void handleSID2A(const uint8_t* data, uint16_t length, const uint8_t sid) {
    if (length < 4) { // subFunction + DID
        sendNegativeResponse(sid, UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT);
        return;
    }

    uint8_t subFunction = data[1];
    uint16_t requestedDid = (data[2] << 8) | data[3];

    int task_index = -1;
    for (int i = 0; i < MAX_PERIODIC_TASKS; i++) {
        if (g_periodicTasks[i].did == requestedDid) {
            task_index = i;
            break;
        }
    }

    if (task_index != -1) { // 해당 DID를 가진 작업을 찾았다면
        uint8_t responseMsg[4];
        responseMsg[0] = UDS_POSITIVE_RESPONSE_SID(sid);
        responseMsg[1] = subFunction;
        responseMsg[2] = (requestedDid >> 8) & 0xFF;
        responseMsg[3] = requestedDid & 0xFF;

        switch (subFunction) {
            case 0x01: // startSending
                g_periodicTasks[task_index].isActive = 1;
                g_periodicTasks[task_index].timer = g_periodicTasks[task_index].intervalMs;

                CANTP_SendResponse(responseMsg, sizeof(responseMsg));
                myPrintf("UDS: Start Periodic DID 0x%04X\n", requestedDid);

                if (MODULE_STM0.ICR.B.CMP1EN == 0) {
                    myPrintf("STM1 interrupt was disabled. Reactivating and scheduling next...\n");
                    // 다음 인터럽트 시점 설정 (현재 시간 + 주기)
                    MODULE_STM0.CMP[1].U = (uint32_t)(MODULE_STM0.TIM0.U + PERIODIC_TICKS);
                    // 인터럽트 플래그 클리어 및 활성화
                    MODULE_STM0.ISCR.B.CMP1IRR = 1U;
                    MODULE_STM0.ICR.B.CMP1EN = 1U;
                }
                break;

            case 0x02: // stopSending
                g_periodicTasks[task_index].isActive = 0;

                CANTP_SendResponse(responseMsg, sizeof(responseMsg));
                myPrintf("UDS: Stop Periodic DID 0x%04X\n", requestedDid);
                break;

            default:
                sendNegativeResponse(sid, UDS_NRC_SUB_FUNCTION_NOT_SUPPORTED);
                break;
        }
    }
    else {
        sendNegativeResponse(sid, UDS_NRC_REQUEST_OUT_OF_RANGE);
    }
}
