/**********************************************************************************************************************
 * \file writedatahandler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "sidhandler.h"
#include "diagnosticsdata.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
// 0x2E: Write Data By Identifier Handler
void handleSID2E(const uint8_t* data, uint16_t length, const uint8_t sid) {
    // 세션 체크: Extended 세션 필요
    if (session_getCurrent() != SESSION_EXTENDED) {
        sendNegativeResponse(sid, UDS_NRC_SUBFUNCTION_NOT_SUPPORTED_IN_ACTIVE_SESSION); // 0x7E
        return;
    }

    if (length < 4) { // SID(1) + DID(2) + Data(1 이상)
        sendNegativeResponse(sid, UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT);
        return;
    }

    uint16_t did = ((uint16_t)data[1] << 8) | data[2];
    switch (did) {
        case UDS_DID_AEB_REMOTE_MASTER_SWITCH:
            if (length == 4) { // 데이터 길이 1바이트 확인
                uint8_t newStatus = data[3];
                if (newStatus == 0x00 || newStatus == 0x01) {
                    g_config.isAebEnabled = (newStatus == 0x01); // config.h 에 선언 가정
                    myPrintf("UDS: AEB Status written to %d\n", g_config.isAebEnabled);

                    uint8_t payload[3]; // SID(1)+DID(2)
                    payload[0] = UDS_POSITIVE_RESPONSE_SID(sid); // 0x6E
                    payload[1] = (did >> 8) & 0xFF;
                    payload[2] = did & 0xFF;

                    CANTP_SendResponse(payload, sizeof(payload));
                }
                else {
                    sendNegativeResponse(sid, UDS_NRC_REQUEST_OUT_OF_RANGE); // 0x31
                }
            }
            else {
                sendNegativeResponse(sid, UDS_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT); // 0x13
            }
            break;
        default:
            sendNegativeResponse(sid, UDS_NRC_REQUEST_OUT_OF_RANGE); // 0x31
            break;
    }
}
