/**********************************************************************************************************************
 * \file diagnosticsdata.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "diagnosticsdata.h"
#include "stm.h"
#include "tof.h"
#include "cantp.h"
#include "ultrasonic.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
PeriodicTransmission g_periodicTasks[MAX_PERIODIC_TASKS] = {
    { .did = UDS_DID_TOF_SENSOR, .intervalMs = 200, .isActive = 0, .timer = 0 },
    { .did = UDS_DID_LEFT_ULTRASONIC_SENSOR, .intervalMs = 300, .isActive = 0, .timer = 0 },
    // 나머지 슬롯은 0으로 초기화
    {0, 0, 0, 0},
    {0, 0, 0, 0},
    {0, 0, 0, 0}
};

SystemConfig g_config;

// ECU가 SID 0x22로 지원하는 모든 DID 목록
uint16 SUPPORTED_DIDS[] = {
        UDS_DID_TOF_SENSOR, // 레이저 센서 길이 측정
        UDS_DID_LEFT_ULTRASONIC_SENSOR, // 좌측 초음파 센서 측정
        UDS_DID_RIGHT_ULTRASONIC_SENSOR, // 우측 초음파 센서 측정
        UDS_DID_REAR_ULTRASONIC_SENSOR, // 후방 초음파 센서 측정
        UDS_DID_ACTIVE_DIAGNOSTIC_SESSION, // Diagnostic Session Identifier(세션 정보 요청)
        UDS_DID_VEHICLE_MANUFACTURER_ECU_PART_NUMBER, // ECU 부품 번호
        UDS_DID_ECU_SERIAL_NUMBER, // ECU 시리얼 번호
        UDS_DID_VEHICLE_IDENTIFICATION_NUMBER, // 차대번호(VIN)
        UDS_DID_ECU_SUPPLIER_INFORMATION, // ECU 공급업체 정보
        UDS_DID_ECU_MANUFACTURING_DATE, // ECU 제조 날짜
        UDS_DID_SUPPORTED_DIDS_LIST  // 지원 DID 목록
};

uint8 NUM_SUPPORTED_DIDS = sizeof(SUPPORTED_DIDS) / sizeof(uint16);

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void UDS_HandlePeriodicTransmission(void) {
    for (int i = 0; i < MAX_PERIODIC_TASKS; i++) {
        // 작업이 활성화 상태이고 타이머가 0이 되었는지 확인
        if (g_periodicTasks[i].isActive && g_periodicTasks[i].timer == 0) {
            uint8_t payload[7];
            uint8_t payloadLen = 0;

            payload[payloadLen++] = (g_periodicTasks[i].did >> 8) & 0xFF;
            payload[payloadLen++] = g_periodicTasks[i].did & 0xFF;

            switch (g_periodicTasks[i].did) {
                case UDS_DID_TOF_SENSOR:
                {
                    uint32_t currentTofValue = tofGetValue();
                    if (currentTofValue != TOF_INVALID_VALUE) {
                        payload[payloadLen++] = (currentTofValue >> 16) & 0xFF;
                        payload[payloadLen++] = (currentTofValue >> 8) & 0xFF;
                        payload[payloadLen++] = currentTofValue & 0xFF;
                    } else {
                        payload[payloadLen++] = (TOF_INVALID_VALUE >> 16);
                        payload[payloadLen++] = (TOF_INVALID_VALUE >> 16);
                        payload[payloadLen++] = TOF_INVALID_VALUE & 0xFF;
                    }

                    CANTP_SendResponse(payload, payloadLen);
                    break;
                }
                case UDS_DID_LEFT_ULTRASONIC_SENSOR:
                {
                    float distance_cm = ultrasonic_getDistanceCm(ULT_LEFT);
                    if (distance_cm < 0)
                    {
                        payload[payloadLen++] = 0xFF;
                        payload[payloadLen++] = 0xFF;
                    }
                    else
                    {
                        uint16_t scaled_distance = (uint16_t)(distance_cm * 10.0f);
                        payload[payloadLen++] = (uint8_t)(scaled_distance >> 8);
                        payload[payloadLen++] = (uint8_t)(scaled_distance & 0xFF);
                    }

                    CANTP_SendResponse(payload, sizeof(payload));
                    break;
                }
            }
            // 다음 전송을 위해 타이머 재설정
            g_periodicTasks[i].timer = g_periodicTasks[i].intervalMs;
        }
    }
}

// 설정값을 초기화
void config_init(void)
{
    // 나중에는 여기서 DFlash의 값을 읽어와 g_config를 채웁니다.

    // 지금은 우선 기본값으로 초기화합니다.
    g_config.isAebEnabled = true; // 기본값은 ON
    strcpy(g_config.partNumber, "RC-CAR-CRTL-V1.0");
    strcpy(g_config.serialNumber, "20250428-001");
    strcpy(g_config.vin, "KR01CAR00PS000001");
    strcpy(g_config.manufacturingDate, "2025-10-22");
    strcpy(g_config.supplier, "Hyundai Autoever");
}
