/**********************************************************************************************************************
 * \file dtc.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "dtc.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
DtcRecord g_dtcStorage[MAX_DTCS] = {
    { UDS_DTC_TOF_TIMEOUT,    0x00 }, // 초기 상태: 고장 없음
    { UDS_DTC_TOF_OUTOFRANGE, 0x00 },
    { UDS_DTC_ULT_LEFT_TIMEOUT, 0x00 },
    { UDS_DTC_ULT_LEFT_OUTOFRANGE, 0x00 },
    { UDS_DTC_ULT_RIGHT_TIMEOUT, 0x00 },
    { UDS_DTC_ULT_RIGHT_OUTOFRANGE, 0x00 },
    { UDS_DTC_ULT_REAR_TIMEOUT, 0x00 },
    { UDS_DTC_ULT_REAR_OUTOFRANGE, 0x00 },
};

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void dtc_updateStatus(uint32 dtc_code, bool is_faulty) {
    for (int i = 0; i < MAX_DTCS; i++) {
        // 장부(배열)에서 해당 DTC 코드를 찾습니다.
        if (g_dtcStorage[i].dtc_code == dtc_code) {
            if (is_faulty) {
                // 고장이 발생했다면, status의 'testFailed' 비트를 1로 설정합니다.
                g_dtcStorage[i].status |= DTC_STATUS_TEST_FAILED;
            }
            else {
                // 고장이 아니라면, 'testFailed' 비트를 0으로 되돌립니다.
                g_dtcStorage[i].status &= ~DTC_STATUS_TEST_FAILED;
            }
            break; // 해당 DTC를 찾았으므로 루프 종료
        }
    }
}
