/**********************************************************************************************************************
 * \file uds.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BSW_SERVICE_DIAGNOSTICS_UDS_H_
#define BSW_SERVICE_DIAGNOSTICS_UDS_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stdint.h>
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define UDS_REQUEST_CAN_ID      0x7E0   // 진단기가 ECU로 보내는 요청 ID
#define UDS_RESPONSE_CAN_ID     0x7E8   // ECU가 진단기로 보내는 응답 ID

#define MAX_PERIODIC_TASKS 5    // 주기적 전송 작업 관리 배열

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 typedef enum {
    UDS_DID_TOF_SENSOR = 0x1000,
    UDS_DID_LEFT_ULTRASONIC_SENSOR = 0x2000,
    UDS_DID_RIGHT_ULTRASONIC_SENSOR = 0x2001,
    UDS_DID_BACK_ULTRASONIC_SENSOR = 0x2002,
} UDS_DID;

typedef struct {
    uint16_t did;               // 관리할 실제 데이터의 DID (UDS_DID 타입)
    uint16_t intervalMs;        // 전송 주기
    uint8_t isActive;           // 활성화 여부
    volatile uint32_t timer;    // 타이머
} PeriodicTransmission;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern PeriodicTransmission g_periodicTasks[MAX_PERIODIC_TASKS];

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void UDS_HandleMessage(const uint8_t* data, uint16_t length);
void sendNegativeResponse(uint8_t sid, uint8_t nrc);
void UDS_HandlePeriodicTransmission(void);

#endif /* BSW_SERVICE_DIAGNOSTICS_UDS_H_ */
